=== frankfloating/web-tp-td/Web/fullrecipe.dtd
<!ELEMENT recipe (title,author+,source?,ingredientlist,utensillist,making,baking?,image*)>
<!ATTLIST recipe
	  level (easy|medium|hard) "easy"
	  price (low|medium|expensive) "low" >


<!ELEMENT title (#PCDATA)>

<!ELEMENT author (lastname, firstname+)>

<!ELEMENT source (#PCDATA)>
<!ATTLIST source
	  href CDATA #IMPLIED>

<!ELEMENT lastname (#PCDATA)>

<!ELEMENT firstname (#PCDATA)>

<!ELEMENT ingredient (#PCDATA)>
<!ATTLIST ingredient
	  qty CDATA #REQUIRED
	  unit (l|dl|cl|kg|gram|unit|tablespoon|pinch) #REQUIRED>


<!ELEMENT ingredientlist (ingredient+)>
<!ATTLIST ingredientlist
	  personnb CDATA #REQUIRED>

<!ELEMENT utensil (#PCDATA)>
<!ATTLIST utensil
	  qty CDATA "1">

<!ELEMENT utensillist (utensil+)>

<!ELEMENT step (#PCDATA)>
<!ATTLIST step
	  time CDATA #IMPLIED>

<!ELEMENT making (#PCDATA|step)*>
<!ATTLIST making
	  time CDATA #IMPLIED>

<!ELEMENT baking EMPTY>
<!ATTLIST baking
	  time CDATA #REQUIRED
	  temperature CDATA #REQUIRED>

<!ELEMENT image EMPTY>
<!ATTLIST image
    name CDATA #REQUIRED>

=== frankfloating/web-tp-td/Web/recette_cuisine_frank_leggett/recette_cuisine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe SYSTEM "fullrecipe.dtd">

<recipe>
    <title>madeleines</title>
    <author>
        <lastname>Leggett</lastname>
        <firstname>Frank</firstname>
    </author>
    <source href="https://www.ricardocuisine.com/en/recipes/5394-lemon-madeleines">Ricardo</source>
    <ingredientlist personnb="4">
        <ingredient qty="18" unit="cl">farine tout usage</ingredient>
        <ingredient qty="0,1" unit="cl">levure chimique</ingredient>
        <ingredient qty="0,1" unit="cl">sel</ingredient>
        <ingredient qty="200" unit="gram">oeuf</ingredient>
        <ingredient qty="12,5" unit="cl">sucre</ingredient>
        <ingredient qty="20" unit="gram">zeste citron</ingredient>
        <ingredient qty="12,5" unit="cl">beurre fondu</ingredient>
    </ingredientlist>
    <utensillist>
        <utensil qty="2">boles</utensil>
        <utensil qty="1">batteur électrique</utensil>
        <utensil qty="1">spatule plastique</utensil>
        <utensil qty="1">moule à madeleine</utensil>
    </utensillist>
    <making time="1 heure">
        <step>Dans un bole mélanger farine, levure chimique et sel</step>
        <step>Dans un autre bole mélanger oeuf, sucre et zeste et battre avec batteur pour 5 minutes</step>
        <step>Avec la spatule plier mélange liquide dans le mélange sec puis faire de même avec beurre</step>
        <step>Couvrir et laisser reposer dans le frigo pour 30 minutes</step>
        <step>remplir moule et cuire pour 10 à 12 minutes jusqu'à le sommet devient doré. Sortir du moule et laisser refroidir</step>
    </making>
    <baking temperature="200 degrès" time="10 à 12 minutes"/>
    <image name="Homemade_French_madeleines.jpg"/>
    <image name="110px-Coquille_Saint_Jacques_(Intérieur).jpg)"/>
</recipe>

=== frankfloating/web-tp-td/Web/recettePateACrepe.xml
<?xml version="1.0" ?>
<!DOCTYPE recipe SYSTEM "fullrecipe.dtd">

<recipe>
  <title> Pâte à  crêpes </title>
  <author>
    <lastname> Alayrangues </lastname>
    <firstname> Sylvie </firstname>
  </author>
  <source  href="http://paradisdescuisiniers.fr">Mamie</source>
  <ingredientlist  personnb="3">
    <ingredient qty="250" unit="gram"> farine </ingredient>
    <ingredient qty="2"   unit="unit"> oeufs </ingredient>
    <ingredient qty="25"  unit="cl"> de lait </ingredient>
    <ingredient qty="25"  unit="cl"> d&apos;eau </ingredient>
    <ingredient qty="2"   unit="tablespoon"> huile </ingredient>
    <ingredient qty="1" unit="pinch"> sel &lt;facultatif&gt; </ingredient>
  </ingredientlist>
  <utensillist>
    <utensil qty="1"> louche </utensil>
    <utensil qty="1"> cuillère en bois </utensil>
    <utensil qty="1"> saladier </utensil>
  </utensillist>
  <making time="5 minutes">
    3 étapes sont nécessaires :
    <step> Mélanger la farine, les oeufs, puis ajouter petit à petit
    le lait et l'eau </step>
    <step> Bien mélanger pour ne pas avoir de grumeaux </step>
    <step> Ajouter l'huile et le sel &lt;facultatif&gt; </step>
  </making>
  <image name="crepe1.jpg"/>
  <image name="crepe2.jpg"/>
</recipe>
